dist: trusty
addons:
  sonarcloud:
    organization: jukeboxroundtable
    secure: RrDw51firtW8aHrFZEDJE6PnDpMo+84Y7QELRaUtwWvh+3O5iUP5f7R4hf3+ZudY2vIWUQo4qmldXsl+WYr64/YRDHXzj+sy4zgsA4NAznSNXtYPH9aY86egTq3gp6xSZCFkFcEu9jz76+T3HvDRyw+YzcA/1PdbWJfZBNohs6dJZ71qvn8coZQNRD82UzGkGSbCP2z9zntEI0yTSR1EpQ+aFenDaeTFeRsWCUrC2raXf3qvmtTfcFmi67N/qWK/Pt2FScp5RpZiPih+rJHRlr6fWP1NJX6PqLxchyGYiCc+OSakJLtCTNA2pHjTuRAvu7QgQSmGmBKAF4ffGE1alCol5V64yS1bpQALsheoK7C2ExkasynslyKcP5/4gseLZVh9t+5LhGapbaodY/qMBKD3oUYAkTHgXxNTUE1CYC0GIxGCQD91+8h9QOJdw9tMA7EHn1+RfzobVMLDAuZhUaCPRVf3sD0Pj+azjgHHZwXxeQ5HqiPqaJdmfutAArKVQKFfeJHKs+NO6LgW+E6AoynrFuMZPqjESbw8RdKBDwhOmQi8dPSMhw1o1Ka9ZTRKpolLr40mxhqQztqjJ/1AHg0ovIUs2W4bbITc16rochv9FqB3SF7VS4Y3/Is8z1xLOW8S8Kksf3YMpAH0YZnmb2R/deGk8CGudHovWa7qpw4=
language: python
python:
- '3.6'
install: pip install -r requirements.txt
script:
- nose2 -v
- sonar-scanner
